### ISSUE TITLE
import netCDF4 error on binder

### ISSUE THREAD

**Issue by dennissergeev** [Unidata/unidata-python-workshop#114]
I was trying to run the workshop notebooks on Binder, specifically the netCDF4 related. However, the netCDF4 library failed to import due to incorrect libjpeg version:
```ipython
import netCDF4
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-62279277fcf6> in <module>()
----> 1 import netCDF4
      2 import numpy as np

/home/main/anaconda2/envs/binder/lib/python3.5/site-packages/netCDF4/__init__.py in <module>()
      1 # init for netCDF4. package
      2 # Docstring comes from extension module _netCDF4.
----> 3 from ._netCDF4 import *
      4 # Need explicit imports for names beginning with underscores
      5 from ._netCDF4 import __doc__, __pdoc__

ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory
```
Is it possible to fix `environment.yml`? Thanks.

**Comment by julienchastang** [comment]
I can confirm the error you are running into, for example, with the `netCDF-Reading.ipynb` mybinder notebook. But I don't think the `environment.yml` file is the source of the problem which works fine for me locally (in a sandboxed docker container, so I know exactly the OS environment I'm dealing with). Rather, I wonder if this is a problem with mybinder itself. I find it peculiar that `anaconda2 ` is referenced since I think we are on anaconda version 3. I don't know the innards of mybinder so that may be a red herring. Also it is strange `libjpeg.so.8` is referenced. We are on version `9` now and version `8` is a few years old. (My local conda environment references `libjpeg.so.9`.)

**Comment by dopplershift** [comment]
My binder has an old version of anaconda, which has a bug that causes it to downgrade the libjpeg (from 9 to 8) when it shouldn't. @ocefpaf has pointed me to IOOS' mybinder Dockerfile which should allow us to skirt around this problem with mybinder.

**Comment by dopplershift** [comment]
It looks like using our own Dockerfile (added in f9982a04d01949f54773416d9c5cc056cf0e70a2) fixed the problem for me. I'm now able to launch a notebook using netCDF4 and run with no problems. Feel free to re-open if you find this is not the case.
