### ISSUE TITLE
Fix environment instructions.

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-python-workshop#53]
At a minimum, we need to put back the *correct* instructions for setting up the ipython/jupyter notebook in our environment. This means installing `ipython-notebook` rather than a hand accumulated list of `tornado`, `jinja`, `pyzmq`, and `ipython`, which is no longer accurate.

Better yet, we could restore the instructions to the use `conda env create` which references the up to date `environment.yml` file.

**Comment by dopplershift** [comment]
Now I see that `environment.yml` was broken in 5adabb9b for.....reasons? 

@julienchastang what was the rationale for replacing the `ipython-notebook` package in `environment.yml`, which Continuum keeps up to date for us with the proper dependencies, with the manual list of `tornado`, `pyzmq`, etc., which is now out of date?

**Comment by julienchastang** [comment]
@dopplershift Thanks for looking into this. I am sure you have more accurate/up-to-date information than I do so doing a wholesale cleanup seems warranted. If there was a rationale, I cannot remember what it was. Moreover, going with an environment.yml or conda-packages.txt is definitely the way to go rather than having unwieldy command line instructions. I'd say go for it. Thanks again.

**Comment by julienchastang** [comment]
Also, we needed `binstar` client which was not there originally and gave workshop attendees trouble. The `binstar` client has since been renamed twice. I think it is now called `anaconda-client`. Thanks for the clarification about `ipython-notebook` versus `tornado`, etc.

**Comment by dopplershift** [comment]
I think we've taken care of this.
